In [18]:
#import
import pandas as pd
import numpy as np

df = pd.read_excel("./data/culdata.xlsx")

In [19]:
df

          순위           관광지명                   도로명주소 중분류 카테고리 소분류 카테고리    검색건수
0          1    신세계백화점센텀시티점      부산 해운대구 센텀남대로 35-0       쇼핑     쇼핑센터  559659
1          2  롯데프리미엄아울렛동부산점      부산 기장군 기장해안로 147-0       쇼핑     쇼핑센터  539663
2          3      김해공항국내선청사      부산 강서구 공항진입로 108-0    기타관광지       공항  492432
3          4        이케아동부산점     부산 기장군 동부산관광3로 17-0       쇼핑     쇼핑센터  403669
4          5      롯데백화점부산본점      부산 부산진구 가야대로 772-0       쇼핑     쇼핑센터  383497
...      ...            ...                     ...      ...      ...     ...
39996  32675      매콤순진 손수제비  부산 동래구 충렬대로237번길 72-28       음식       한식       3
39997  32675           에슈에뜨   부산 금정구 장전온천천로79번길 9-0       음식     카페기타       3
39998  32675     스시투어NC부산대점    부산 금정구 부산대학로63번길 2-0       음식       일식       3
39999  32675        1부두후생식당         부산 중구 충장대로 24-0       음식       한식       3
40000  32675            장관청     부산 동래구 명륜로94번길 36-6    역사관광지    문화유적지       3

[40001 rows x 6 columns]

In [20]:
df_midle = df.groupby(["중분류 카테고리"]).sum()
type(df_midle)

df_midle.sort_values(by='검색건수', ascending = False)
df_midle=df_midle.drop(["순위"], axis = 1)
df_midle

                  검색건수
중분류 카테고리
공연/행사           267098
기타관광지          1834106
레포츠(육상/해상/항공)  1140262
문화시설            831919
쇼핑             8795691
숙박             2803611
역사관광지           676826
음식             8540169
자연관광지          3031354
휴양관광지           405831

In [21]:
df_sub = df.groupby(["소분류 카테고리"]).sum().sort_values(by='검색건수',  ascending = False)
df_sub = df_sub.drop(["순위"], axis = 1)
df_sub

             검색건수
소분류 카테고리
쇼핑센터      5775821
한식        2626041
호텔        1996992
전문음식점     1662123
쇼핑기타      1590367
...           ...
양궁/곡궁         344
데이트코스         238
음악카페           72
호수             28
약수터             3

[102 rows x 1 columns]

In [22]:
#카테고리별 분류
df_cate = df.groupby(["중분류 카테고리", "소분류 카테고리"]).sum()
df_cate= df_cate.drop(["순위"], axis = 1)
df_cate

                     검색건수
중분류 카테고리 소분류 카테고리
공연/행사    공연장        62634
         극장        204464
기타관광지    공항        794105
         관광단지        3180
         관광명소기타    451401
...                   ...
휴양관광지    수족관        46644
         온천         66598
         유원지         7238
         종합위락시설     37071
         테마파크       96947

[102 rows x 1 columns]

In [23]:
df_cate.to_csv("./save/cate.csv")

### 숙박시설 제거

In [24]:
#숙박시설제거
df_acc = df[df["중분류 카테고리"] != '숙박']
df_acc

          순위           관광지명                   도로명주소 중분류 카테고리 소분류 카테고리    검색건수
0          1    신세계백화점센텀시티점      부산 해운대구 센텀남대로 35-0       쇼핑     쇼핑센터  559659
1          2  롯데프리미엄아울렛동부산점      부산 기장군 기장해안로 147-0       쇼핑     쇼핑센터  539663
2          3      김해공항국내선청사      부산 강서구 공항진입로 108-0    기타관광지       공항  492432
3          4        이케아동부산점     부산 기장군 동부산관광3로 17-0       쇼핑     쇼핑센터  403669
4          5      롯데백화점부산본점      부산 부산진구 가야대로 772-0       쇼핑     쇼핑센터  383497
...      ...            ...                     ...      ...      ...     ...
39996  32675      매콤순진 손수제비  부산 동래구 충렬대로237번길 72-28       음식       한식       3
39997  32675           에슈에뜨   부산 금정구 장전온천천로79번길 9-0       음식     카페기타       3
39998  32675     스시투어NC부산대점    부산 금정구 부산대학로63번길 2-0       음식       일식       3
39999  32675        1부두후생식당         부산 중구 충장대로 24-0       음식       한식       3
40000  32675            장관청     부산 동래구 명륜로94번길 36-6    역사관광지    문화유적지       3

[38091 rows x 6 columns]

In [25]:
#특정 키워드가 포함된 행 추출
df[df["관광지명"].str.contains('부두')]

          순위          관광지명              도로명주소 중분류 카테고리 소분류 카테고리   검색건수
48        49         신선대부두              부산 남구    자연관광지       항구  69209
98        99       부산항제5부두   부산 동구 충장대로 314-0    자연관광지       항구  41849
156      157          감만부두              부산 남구    자연관광지       항구  25361
354      355       부산항제7부두              부산 남구    자연관광지       항구  11593
368      369        감천중앙부두             부산 사하구    자연관광지       항구  11053
740      741        감천서편부두             부산 사하구    자연관광지       항구   5583
836      836        감만시민부두              부산 남구    자연관광지       항구   5015
846      847       부산항제8부두              부산 남구    자연관광지       항구   4956
1013    1014        감천동편부두              부산 서구    자연관광지       항구   4195
1038    1039       부산항제4부두   부산 동구 충장대로 206-0    자연관광지       항구   4084
1192    1193       부산항제2부두    부산 중구 충장대로 54-0    자연관광지       항구   3507
1355    1356       부산항제1부두              부산 중구    자연관광지       항구   3059
1749    1750         신감만부두              부산 남구    자연관광지       항구   2320
2317    2317          동명부두     부산 남구 북항로 17-0    자연관광지       항구   1701
2926    2927  세븐일레븐부산감만부두점              부산 남구       쇼핑     쇼핑기타   1222
3419    3417   부산신항남컨테이너부두  부산 강서구 신항남로 454-0    자연관광지       항구    959
3548    3545       용호부두장치장    부산 남구 분포로 66-40    자연관광지       항구    902
4729    4728       CU감만부두점    부산 남구 북항로 105-0       쇼핑     쇼핑기타    571
5281    5277           부두길              부산 동구    기타관광지   관광명소기타    462
5881    5882   부산항부두관리감천부두             부산 사하구    자연관광지       항구    373
5943    5942       용호만매립부두              부산 남구    자연관광지       항구    365
6169    6160       부산항제3부두   부산 동구 충장대로 164-0    자연관광지       항구    342
6561    6559     북빈물량장대체부두             부산 영도구    자연관광지       항구    302
8234    8211      신감만부두방파제              부산 남구    자연관광지      방파제    183
12679  12669          연안부두              부산 중구    자연관광지       항구     65
13823  13772      감만부두공용관리    부산 남구 북항로 105-0       음식       한식     52
16843  16695    중앙부두부산중앙부두     부산 동구 충장대로 0-0    자연관광지       항구     31
16890  16891    제2부두노무자급식소    부산 중구 충장대로 54-0       음식       한식     30
20337  20247      CU신선대부두점    부산 남구 신선로 294-0       쇼핑     쇼핑기타     18
20378  20247   부산해양경찰서전용부두              부산 남구    자연관광지       항구     18
29859  28231     CU감만부두2호점    부산 남구 북항로 147-0       쇼핑     쇼핑기타      6
32326  31312        동명부두매점     부산 남구 북항로 17-0       음식       한식      4
39999  32675       1부두후생식당    부산 중구 충장대로 24-0       음식       한식      3

In [26]:
#구별 분류
df_acc["도로명주소"].str.split(" ", expand = True)[1]

0        해운대구
1         기장군
2         강서구
3         기장군
4        부산진구
         ...
39996     동래구
39997     금정구
39998     금정구
39999      중구
40000     동래구
Name: 1, Length: 38091, dtype: object

In [27]:
df_acc["구군명"]= df_acc["도로명주소"].str.split(" ", expand = True)[1]

C:\Users\ad\AppData\Local\Temp/ipykernel_7792/4082840087.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_acc["구군명"]= df_acc["도로명주소"].str.split(" ", expand = True)[1]

In [36]:
#소분류별 분류
df_acc.sort_values(by = '소분류 카테고리', ascending = True).to_csv("./save/데이터.csv")

In [29]:
df_acc = df_acc[(df_acc["중분류 카테고리"] != '쇼핑') & \
               (df_acc["중분류 카테고리"] != '음식')]
df_acc

,순위,관광지명,도로명주소,중분류 카테고리,소분류 카테고리,검색건수,구군명
2,3,김해공항국내선청사,부산 강서구 공항진입로 108-0,기타관광지,공항,492432,강서구
7,8,김해국제공항,부산 강서구 공항진입로 108-0,기타관광지,공항,301673,강서구
8,9,송정해수욕장,부산 해운대구 송정해변로 62-0,자연관광지,해수욕장,285852,해운대구
9,10,광안리해수욕장,부산 수영구 광안해변로 219-0,자연관광지,해수욕장,262135,수영구
10,11,해운대해수욕장,부산 해운대구 해운대해변로 264-0,자연관광지,해수욕장,253659,해운대구
...,...,...,...,...,...,...,...
39912,32675,로얄헬스클럽,부산 부산진구 부전로152번길 27-0,레포츠(육상/해상/항공),레저/스포츠기타,3,부산진구
39945,32675,SG골프고고골프클럽,부산 강서구 명지국제8로 270-0,레포츠(육상/해상/항공),골프장,3,강서구
39952,32675,청사포어항남방파제등대,부산 해운대구,자연관광지,등대,3,해운대구
39973,32675,SG골프삼현스크린,부산 사상구 백양대로 949-10,레포츠(육상/해상/항공),골프장,3,사상구
40000,32675,장관청,부산 동래구 명륜로94번길 36-6,역사관광지,문화유적지,3,동래구

In [30]:
#정렬하기
df_Gu = df_acc.sort_values(by= '구군명').reset_index(drop = True)
df_Gu

,순위,관광지명,도로명주소,중분류 카테고리,소분류 카테고리,검색건수,구군명
0,3,김해공항국내선청사,부산 강서구 공항진입로 108-0,기타관광지,공항,492432,강서구
1,6976,혜지우스크린골프,부산 강서구 명지오션시티9로 43-0,레포츠(육상/해상/항공),골프장,263,강서구
2,2077,낚시야부산가락점,부산 강서구 가락대로961번길 54-0,레포츠(육상/해상/항공),낚시,1938,강서구
3,2067,SG골프대명스크린,부산 강서구 명지국제8로10번길 12-0,레포츠(육상/해상/항공),골프장,1944,강서구
4,7038,대저생태공원야구장B,부산 강서구,기타관광지,운동장,258,강서구
...,...,...,...,...,...,...,...
4086,32675,비프빌리지,부산 해운대구,기타관광지,관광명소기타,3,해운대구
4087,1556,미포철길,부산 해운대구 달맞이길62번길 13-0,기타관광지,관광명소기타,2641,해운대구
4088,6559,마블피트니스해운대점,부산 해운대구 해운대로469번길 8-0,레포츠(육상/해상/항공),레저/스포츠기타,302,해운대구
4089,22532,옥봉산쉼터,부산 해운대구,레포츠(육상/해상/항공),여행/레저기타,13,해운대구
4090,8670,베어브라더,부산 해운대구 송정광어골로 21-0,레포츠(육상/해상/항공),레저/스포츠기타,163,해운대구

In [31]:
df_Gu_list = df_Gu["구군명"].unique()
df_Gu_list

array(['강서구', '금정구', '기장군', '남구', '동구', '동래구', '부산진구', '북구', '사상구', '사하구',
       '서구', '수영구', '연제구', '영도구', '중구', '해운대구'], dtype=object)

In [32]:
#구별 분리
dic_list = {}
for i in range(0, len(df_Gu_list)) :
    df2 = pd.DataFrame() #깨끗한 데이터 프레임
    df2 = df_Gu[df_Gu["구군명"]== df_Gu_list[i]] #꺠끗한 데이터 프레임에 자료 삽입
    dic_list[df_Gu_list[i]] = df2 #키 값별 데이터 프레임

In [33]:
#딕셔너리에 있는거 하나씩 불러오기
dic_list["동구"]

,순위,관광지명,도로명주소,중분류 카테고리,소분류 카테고리,검색건수,구군명
1333,32675,부산항시민해수온천야외수영장,부산 동구 충장대로 206-0,기타관광지,수영장,3,동구
1334,32675,관음사,부산 동구 망양로593번길 21-10,역사관광지,절,3,동구
1335,3034,클래스윔스포츠센터초량지점,부산 동구 중앙대로 319-0,기타관광지,수영장,1153,동구
1336,6269,가온아트홀,부산 동구 자성로133번길 10-0,공연/행사,공연장,330,동구
1337,3305,북두칠성도서관,부산 동구 충장대로 160-0,문화시설,문화생활시설기타,1006,동구
...,...,...,...,...,...,...,...
1466,3855,부산광역시립중앙도서관수정분관,부산 동구 홍곡로 53-0,문화시설,문화생활시설기타,791,동구
1467,13674,이바구공작소,부산 동구 망양로486번길 14-13,문화시설,문화생활시설기타,53,동구
1468,31312,자성로지하도,부산 동구,기타관광지,관광명소기타,4,동구
1469,13866,자성대,부산 동구 자성로 99-0,역사관광지,문화유적지,51,동구
1470,15076,부산항축제(부산항국제여객터미널),부산 동구 충장대로 206-0,기타관광지,축제,41,동구

In [34]:
df_Gu[df_Gu["구군명"] == df_Gu_list(1)]

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
# 중분류 카테고리별 개수
df.groupby(["중분류 카테고리"]).size().to_csv("./save/중분류.csv")

In [ ]:
#소분류 카테고리별 개수
df.groupby(["소분류 카테고리"]).size().to_csv("./save./소분류.csv")

In [ ]:
df_acc[df_acc["관광지명"].str.contains('관광')]

In [ ]:
df_acc[df_acc["관광지명"].str.contains('편의점')]

In [ ]:
df_acc[(df_acc[df_acc["관광지명"].str.contains('CU')) & \
        (df_acc[df_acc["관광지명"].str.contains('GS')) & \
        (df_acc[df_acc["관광지명"].str.contains('이마트')) & \
        (df_acc[df_acc["관광지명"].str.contains('세븐일레븐')) & \
        (df_acc[df_acc["관광지명"].str.contains('미니스톱'))]

In [ ]:
#카테고리별 분류
#pd.set_option('display.max_row', 30)
df_cate = df.groupby(["중분류 카테고리", "소분류 카테고리"]).size()
df_cate.reset_index()

In [ ]:
pd.set_option('display.max_row', 100)
df[df["중분류 카테고리"] == '공연/행사']

In [40]:
df1 = df[(df["중분류 카테고리"]== '공연/행사')  |\
    (df["중분류 카테고리"]== '역사관광지') | \
    (df["중분류 카테고리"] == '휴양관광지') | \
    (df["중분류 카테고리"] == '문화시설')]

df1

          순위      관광지명                 도로명주소 중분류 카테고리 소분류 카테고리    검색건수
12        13     해동용궁사       부산 기장군 용궁길 86-0    역사관광지        절  191384
22        23     BEXCO    부산 해운대구 APEC로 55-0     문화시설      전시장  122503
23        24       태종대       부산 영도구 전망로 24-0    역사관광지    문화유적지  118816
41        42       범어사     부산 금정구 범어사로 250-0    역사관광지        절   81191
52        53  부산어린이대공원     부산 부산진구 새싹로 295-0    휴양관광지     테마파크   66601
...      ...       ...                   ...      ...      ...     ...
39532  32675   시네마테크부산  부산 해운대구 수영강변대로 120-0    공연/행사       극장       3
39859  32675   미월드(폐장)    부산 수영구 광안해변로 361-0    휴양관광지     놀이시설       3
39885  32675     청목수목원   부산 부산진구 양성로6번길 53-0    휴양관광지     동식물원       3
39896  32675       정해사  부산 영도구 와치로161번길 31-3    역사관광지        절       3
40000  32675       장관청   부산 동래구 명륜로94번길 36-6    역사관광지    문화유적지       3

[1382 rows x 6 columns]

In [42]:
df1["구군명"]= df1["도로명주소"].str.split(" ", expand = True)[1]

C:\Users\ad\AppData\Local\Temp/ipykernel_7792/3655605675.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["구군명"]= df1["도로명주소"].str.split(" ", expand = True)[1]

In [44]:
df1

          순위      관광지명                 도로명주소 중분류 카테고리 소분류 카테고리    검색건수   구군명
12        13     해동용궁사       부산 기장군 용궁길 86-0    역사관광지        절  191384   기장군
22        23     BEXCO    부산 해운대구 APEC로 55-0     문화시설      전시장  122503  해운대구
23        24       태종대       부산 영도구 전망로 24-0    역사관광지    문화유적지  118816   영도구
41        42       범어사     부산 금정구 범어사로 250-0    역사관광지        절   81191   금정구
52        53  부산어린이대공원     부산 부산진구 새싹로 295-0    휴양관광지     테마파크   66601  부산진구
...      ...       ...                   ...      ...      ...     ...   ...
39532  32675   시네마테크부산  부산 해운대구 수영강변대로 120-0    공연/행사       극장       3  해운대구
39859  32675   미월드(폐장)    부산 수영구 광안해변로 361-0    휴양관광지     놀이시설       3   수영구
39885  32675     청목수목원   부산 부산진구 양성로6번길 53-0    휴양관광지     동식물원       3  부산진구
39896  32675       정해사  부산 영도구 와치로161번길 31-3    역사관광지        절       3   영도구
40000  32675       장관청   부산 동래구 명륜로94번길 36-6    역사관광지    문화유적지       3   동래구

[1382 rows x 7 columns]

In [67]:
df_list1 = df1.drop(['순위'], axis = 1).reset_index(drop = True)
df_list1

          관광지명                 도로명주소 중분류 카테고리 소분류 카테고리    검색건수   구군명
0        해동용궁사       부산 기장군 용궁길 86-0    역사관광지        절  191384   기장군
1        BEXCO    부산 해운대구 APEC로 55-0     문화시설      전시장  122503  해운대구
2          태종대       부산 영도구 전망로 24-0    역사관광지    문화유적지  118816   영도구
3          범어사     부산 금정구 범어사로 250-0    역사관광지        절   81191   금정구
4     부산어린이대공원     부산 부산진구 새싹로 295-0    휴양관광지     테마파크   66601  부산진구
...        ...                   ...      ...      ...     ...   ...
1377   시네마테크부산  부산 해운대구 수영강변대로 120-0    공연/행사       극장       3  해운대구
1378   미월드(폐장)    부산 수영구 광안해변로 361-0    휴양관광지     놀이시설       3   수영구
1379     청목수목원   부산 부산진구 양성로6번길 53-0    휴양관광지     동식물원       3  부산진구
1380       정해사  부산 영도구 와치로161번길 31-3    역사관광지        절       3   영도구
1381       장관청   부산 동래구 명륜로94번길 36-6    역사관광지    문화유적지       3   동래구

[1382 rows x 6 columns]

In [69]:
df_list2 = df_list1.drop(['검색건수'], axis = 1)
df_list2

          관광지명                 도로명주소 중분류 카테고리 소분류 카테고리   구군명
0        해동용궁사       부산 기장군 용궁길 86-0    역사관광지        절   기장군
1        BEXCO    부산 해운대구 APEC로 55-0     문화시설      전시장  해운대구
2          태종대       부산 영도구 전망로 24-0    역사관광지    문화유적지   영도구
3          범어사     부산 금정구 범어사로 250-0    역사관광지        절   금정구
4     부산어린이대공원     부산 부산진구 새싹로 295-0    휴양관광지     테마파크  부산진구
...        ...                   ...      ...      ...   ...
1377   시네마테크부산  부산 해운대구 수영강변대로 120-0    공연/행사       극장  해운대구
1378   미월드(폐장)    부산 수영구 광안해변로 361-0    휴양관광지     놀이시설   수영구
1379     청목수목원   부산 부산진구 양성로6번길 53-0    휴양관광지     동식물원  부산진구
1380       정해사  부산 영도구 와치로161번길 31-3    역사관광지        절   영도구
1381       장관청   부산 동래구 명륜로94번길 36-6    역사관광지    문화유적지   동래구

[1382 rows x 5 columns]

In [83]:
file_path= pd.read_excel("./data/busan_pop.xlsx"
                        , sheet_name = "시트1")
file_path

     구군명       구군명(영어)
0    강서구    Gangseo-gu
1    금정구  Geumjeong-gu
2    기장군    Gijang-gun
3     남구        Nam-gu
4     동구       Dong-gu
5    동래구    Dongnae-gu
6   부산진구   Busanjin-gu
7     북구        Buk-gu
8    사상구     Sasang-gu
9    사하구       Saha-gu
10    서구        Seo-gu
11   수영구    Suyeong-gu
12   연제구     Yeonje-gu
13   영도구    Yeongdo-gu
14    중구       Jung-gu
15  해운대구   Haeundae-gu

In [84]:
#딕셔너리로 변환 작업 1: .to_dict("recrods")  - 리스트형태의 딕셔너리
dic_gu = file_path.to_dict("records")

In [101]:
df_gu_dic = {}

#for 문
for i in range(0, len(file_path)) :
    df_gu_dic[dic_gu[i]["구군명"]]= dic_gu[i]["구군명(영어)"]

In [105]:
df_gu_dic

{'강서구': 'Gangseo-gu',
 '금정구': 'Geumjeong-gu',
 '기장군': 'Gijang-gun',
 '남구': 'Nam-gu',
 '동구': 'Dong-gu',
 '동래구': 'Dongnae-gu',
 '부산진구': 'Busanjin-gu',
 '북구': 'Buk-gu',
 '사상구': 'Sasang-gu',
 '사하구': 'Saha-gu',
 '서구': 'Seo-gu',
 '수영구': 'Suyeong-gu',
 '연제구': 'Yeonje-gu',
 '영도구': 'Yeongdo-gu',
 '중구': 'Jung-gu',
 '해운대구': 'Haeundae-gu'}

In [107]:
df_f=df_list2.rename(rows = df_gu_dic)

TypeError: rename() got an unexpected keyword argument 'rows'

### inner join 사용

In [93]:
df_F= pd.merge(df_list2, file_path, how = 'inner', on = '구군명')

In [108]:
df_F.drop('구군명', axis = 1)

df_F.to_csv("./save/data1.csv")

In [109]:
df_F

             관광지명                도로명주소 중분류 카테고리  소분류 카테고리  구군명     구군명(영어)
0           해동용궁사      부산 기장군 용궁길 86-0    역사관광지         절  기장군  Gijang-gun
1             장안사     부산 기장군 장안로 482-0    역사관광지         절  기장군  Gijang-gun
2            아홉산숲      부산 기장군 미동길 37-1    휴양관광지      동식물원  기장군  Gijang-gun
3         국립부산과학관  부산 기장군 동부산관광6로 59-0     문화시설       과학관  기장군  Gijang-gun
4           아난티코브  부산 기장군 기장해안로 268-32    휴양관광지    종합위락시설  기장군  Gijang-gun
...           ...                  ...      ...       ...  ...         ...
1377         자화정사  부산 서구 천마로113번길 16-1    역사관광지         절   서구      Seo-gu
1378          용문사     부산 서구 암남공원로 60-4    역사관광지         절   서구      Seo-gu
1379          금수암  부산 서구 꽃마을로87번길 18-0    역사관광지         절   서구      Seo-gu
1380          보문사     부산 서구 천마산로 227-0    역사관광지         절   서구      Seo-gu
1381  경남고등학교덕형도서관  부산 서구 망양로111번길 65-0     문화시설  문화생활시설기타   서구      Seo-gu

[1382 rows x 6 columns]